io/touchstone.py: strip leading spaces, close #1339.
The following is the Touchstone header generated by an old Rohde & Schwarz ZVR VNA.

    !--------------------------------------------------------------------------------------------------------------
    ! ZVR, 1.20 beta F
    !--------------------------------------------------------------------------------------------------------------
    ! symbol freq-unit parameter-type data-format keyword impedance-ohm
      #      HZ        S              DB          R       50
    !--------------------------------------------------------------------------------------------------------------
    ! freq                dbS11          angS11          dbS21          angS21          dbS12          angS12          dbS22          angS22

It appears that scikit-rf has been confused by the leading spaces before `#`,
tries to parse the line as a data line, triggering the error:

    ValueError: could not convert string to float: '#'

This commit strips all leading spaces via lstrip() before reading a line
from the Touchstone file, so that option lines are correctly identified
in spite of leading spaces.

Signed-off-by: Yifeng Li <tomli@tomli.me>