is_from_hfss(): fix TypeError when comments is None
This fixes:
[...]/skrf/io/touchstone.py in is_from_hfss(self)
    417         '''
    418         status = False
--> 419         if 'exported from hfss' in str.lower(self.comments):
    420             status = True
    421         return status

TypeError: descriptor 'lower' requires a 'str' object but received a 'NoneType'

... when comments is None. Return False instead.